package internal

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func findCheck(checks []Check, name string) (Check, bool) {
	for _, c := range checks {
		if c.Name == name {
			return c, true
		}
	}
	return Check{}, false
}

func noLookPath(string) (string, error) { return "", fmt.Errorf("not found") }

func TestRunDoctorHookAndGitChecks(t *testing.T) {
	env := newTestEnv(t, twoProfiles+"\n[cloud]\nremote = \"x\"\n")
	stubKeychain(t, false)
	home := t.TempDir()

	checks := RunDoctorWithOptions(env.load(t), env.profilesBase(), DoctorOptions{HomeDir: home, LookPath: noLookPath})
	if c, _ := findCheck(checks, "shell hook"); c.Status != "warn" {
		t.Errorf("hook should be missing: %+v", c)
	}
	if c, _ := findCheck(checks, "git binary"); c.Status != "error" {
		t.Errorf("git should be reported missing when cloud is configured: %+v", c)
	}

	mustWrite(t, filepath.Join(home, ".zshrc"), "eval \"$(cpm hook)\"\n")
	okLook := func(name string) (string, error) { return "/usr/bin/" + name, nil }
	checks = RunDoctorWithOptions(env.load(t), env.profilesBase(), DoctorOptions{HomeDir: home, LookPath: okLook})
	if c, _ := findCheck(checks, "shell hook"); c.Status != "ok" || !strings.HasSuffix(c.Detail, ".zshrc") {
		t.Errorf("hook should be found: %+v", c)
	}
	if c, _ := findCheck(checks, "git binary"); c.Status != "ok" {
		t.Errorf("git should be ok: %+v", c)
	}

	// No cloud section: no git check.
	env2 := newTestEnv(t, twoProfiles)
	checks = RunDoctorWithOptions(env2.load(t), env2.profilesBase(), DoctorOptions{HomeDir: home, LookPath: noLookPath})
	if _, found := findCheck(checks, "git binary"); found {
		t.Error("git check must only run when cloud is configured")
	}
}

func TestRunDoctorUnknownKeys(t *testing.T) {
	env := newTestEnv(t, "[profiles.work]\nmodl = \"x\"\n")
	stubKeychain(t, false)
	checks := RunDoctorWithOptions(env.load(t), env.profilesBase(), DoctorOptions{HomeDir: t.TempDir(), LookPath: noLookPath})
	c, found := findCheck(checks, "config keys")
	if !found || c.Status != "warn" || !strings.Contains(c.Detail, "profiles.work.modl") {
		t.Errorf("unknown key not reported: %+v", c)
	}
}

func TestRunDoctorWrapperOutdated(t *testing.T) {
	env := newTestEnv(t, twoProfiles)
	stubKeychain(t, false)
	captureOutput(t)
	if err := InstallProfiles(env.load(t), env.ConfigPath, InstallOptions{}); err != nil {
		t.Fatal(err)
	}
	opts := DoctorOptions{HomeDir: t.TempDir(), LookPath: noLookPath}
	checks := RunDoctorWithOptions(env.load(t), env.profilesBase(), opts)
	if c, _ := findCheck(checks, "profile/work/wrapper"); c.Status != "ok" {
		t.Errorf("fresh wrapper should be ok: %+v", c)
	}

	mustWrite(t, filepath.Join(env.BinDir, "claude-work"), "#!/bin/bash\n# Generated by cpm (Claude Profile Manager)\nexec claude\n")
	checks = RunDoctorWithOptions(env.load(t), env.profilesBase(), opts)
	if c, _ := findCheck(checks, "profile/work/wrapper"); c.Status != "warn" || !strings.Contains(c.Detail, "outdated") {
		t.Errorf("stale wrapper not detected: %+v", c)
	}
	os.Remove(filepath.Join(env.BinDir, "claude-work"))
	checks = RunDoctorWithOptions(env.load(t), env.profilesBase(), opts)
	if c, _ := findCheck(checks, "profile/work/wrapper"); !strings.Contains(c.Detail, "missing") {
		t.Errorf("missing wrapper not detected: %+v", c)
	}
}

func TestRunDoctorVerifyKeychain(t *testing.T) {
	env := newTestEnv(t, "[profiles.work]\n")
	mustMkdir(t, filepath.Join(env.profilesBase(), "work"))
	stubKeychain(t, true)
	prev := keychainRead
	past := time.Now().Add(-time.Hour)
	keychainRead = func(service, account string) ([]byte, error) {
		return []byte(fmt.Sprintf(`{"claudeAiOauth":{"expiresAt":%d,"subscriptionType":"max"}}`, past.UnixMilli())), nil
	}
	t.Cleanup(func() { keychainRead = prev })
	opts := DoctorOptions{HomeDir: t.TempDir(), LookPath: noLookPath}

	checks := RunDoctorWithOptions(env.load(t), env.profilesBase(), opts)
	if c, _ := findCheck(checks, "profile/work/credentials"); c.Status != "ok" {
		t.Errorf("without --verify the keychain login is ok: %+v", c)
	}

	opts.Verify = true
	checks = RunDoctorWithOptions(env.load(t), env.profilesBase(), opts)
	if c, _ := findCheck(checks, "profile/work/credentials"); c.Status != "warn" || !strings.Contains(c.Detail, "expired") {
		t.Errorf("--verify should report the expired token: %+v", c)
	}

	future := time.Now().Add(time.Hour)
	keychainRead = func(service, account string) ([]byte, error) {
		return []byte(fmt.Sprintf(`{"claudeAiOauth":{"expiresAt":%d,"subscriptionType":"max"}}`, future.UnixMilli())), nil
	}
	checks = RunDoctorWithOptions(env.load(t), env.profilesBase(), opts)
	if c, _ := findCheck(checks, "profile/work/credentials"); c.Status != "ok" || !strings.Contains(c.Detail, "(max)") || !strings.Contains(c.Detail, "valid until") {
		t.Errorf("--verify should show subscription and expiry: %+v", c)
	}

	// Read failure keeps the plain status.
	keychainRead = func(string, string) ([]byte, error) { return nil, fmt.Errorf("denied") }
	checks = RunDoctorWithOptions(env.load(t), env.profilesBase(), opts)
	if c, _ := findCheck(checks, "profile/work/credentials"); c.Status != "ok" {
		t.Errorf("read failure must not fail the check: %+v", c)
	}
}
