package internal

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const marker = "# Generated by cpm (Claude Profile Manager)"

// legacyMarker is what pre-rename versions wrote; stale wrappers from those
// versions still need cleaning up.
const legacyMarker = "# Generated by claude-auth-switch"

// wrapperPrefix is the name every generated wrapper carries: claude-<profile>.
const wrapperPrefix = "claude-"

// markerScanLines is how far into a file the marker may appear for it to count
// as a generated wrapper header.
const markerScanLines = 5

// GenerateWrapper renders the bash wrapper script for a profile.
func GenerateWrapper(name string, profileDir string, profile *Profile) string {
	spec := BuildLaunchSpec(name, profileDir, profile)
	var b strings.Builder

	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString(marker + "\n")
	fmt.Fprintf(&b, "# Profile: %s — %s\n", name, profile.Description)
	b.WriteString("set -euo pipefail\n\n")

	b.WriteString("# Unset inherited CLAUDE_*/ANTHROPIC_* env vars to avoid interference\n")
	b.WriteString("while IFS= read -r varname; do\n")
	b.WriteString("  unset \"$varname\"\n")
	b.WriteString("done < <(compgen -v | grep -E \"^(CLAUDE_|ANTHROPIC_)\" || true)\n\n")

	for _, v := range spec.Env {
		fmt.Fprintf(&b, "export %s=%s\n", v.Key, ShellQuote(v.Value))
	}
	b.WriteString("\n")

	b.WriteString("# Subcommands only need the environment, not profile flags\n")
	fmt.Fprintf(&b, "case \"${1:-}\" in\n  %s) exec claude \"$@\" ;;\nesac\n\n", strings.Join(bypassSubcommands, "|"))

	b.WriteString("extra=()\n")
	for _, d := range spec.AddDirs {
		fmt.Fprintf(&b, "extra+=(--add-dir %s)\n", ShellQuote(d))
	}
	if spec.Model != "" {
		b.WriteString("# Default model (overridden if --model is passed on command line)\n")
		b.WriteString("has_model=false\n")
		b.WriteString("for arg in \"$@\"; do\n")
		b.WriteString("  case \"$arg\" in\n")
		b.WriteString("    --model|--model=*) has_model=true; break ;;\n")
		b.WriteString("  esac\n")
		b.WriteString("done\n")
		fmt.Fprintf(&b, "if [ \"$has_model\" = false ]; then extra+=(--model %s); fi\n", ShellQuote(spec.Model))
	}
	b.WriteString("\n")

	// ${extra[@]+"${extra[@]}"} expands to nothing for an empty array without
	// tripping `set -u` on bash 3.2 (macOS).
	b.WriteString("exec claude ${extra[@]+\"${extra[@]}\"} \"$@\"\n")

	return b.String()
}

func InstallWrapper(scriptPath, content string) error {
	dir := filepath.Dir(scriptPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	existing, err := os.ReadFile(scriptPath)
	if err == nil && string(existing) == content {
		return nil
	}

	if err := os.WriteFile(scriptPath, []byte(content), 0o755); err != nil {
		return err
	}
	outf("  installed %s\n", scriptPath)
	return nil
}

func CleanupStaleScripts(binDir string, activeNames map[string]bool) {
	entries, err := os.ReadDir(binDir)
	if err != nil {
		return
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if activeNames[entry.Name()] {
			continue
		}
		// Wrappers are always named claude-<profile>. Anything else in bin_dir
		// is someone else's binary — including cpm itself, which carries the
		// marker as a compiled-in string constant.
		if !strings.HasPrefix(entry.Name(), wrapperPrefix) {
			continue
		}
		path := filepath.Join(binDir, entry.Name())
		if !isGeneratedWrapper(path) {
			continue
		}
		os.Remove(path)
		outf("  removed stale script %s\n", path)
	}
}

// isGeneratedWrapper reports whether path is a shell script cpm generated,
// judged by the marker appearing in its header rather than anywhere in the
// file — a binary that merely embeds the string must not match.
func isGeneratedWrapper(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	head := make([]byte, 512)
	n, err := f.Read(head)
	if err != nil && n == 0 {
		return false
	}
	head = head[:n]

	if !strings.HasPrefix(string(head), "#!") {
		return false
	}
	lines := strings.SplitN(string(head), "\n", markerScanLines+1)
	for i, line := range lines {
		if i >= markerScanLines {
			break
		}
		trimmed := strings.TrimSpace(line)
		if trimmed == marker || trimmed == legacyMarker {
			return true
		}
	}
	return false
}
