package internal

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const marker = "# Generated by cpm (Claude Profile Manager)"

// legacyMarker is what pre-rename versions wrote; stale wrappers from those
// versions still need cleaning up.
const legacyMarker = "# Generated by claude-auth-switch"

// wrapperPrefix is the name every generated wrapper carries: claude-<profile>.
const wrapperPrefix = "claude-"

// markerScanLines is how far into a file the marker may appear for it to count
// as a generated wrapper header.
const markerScanLines = 5

var subcommands = "mcp|auth|doctor|install|setup-token|update|upgrade|agents|auto-mode|plugin|plugins"

func GenerateWrapper(name string, profileDir string, profile *Profile) string {
	var b strings.Builder

	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString(marker + "\n")
	fmt.Fprintf(&b, "# Profile: %s — %s\n", name, profile.Description)
	b.WriteString("set -euo pipefail\n\n")

	// Unset inherited CLAUDE_*/ANTHROPIC_* env vars
	b.WriteString("# Unset inherited CLAUDE_*/ANTHROPIC_* env vars to avoid interference\n")
	b.WriteString("while IFS= read -r varname; do\n")
	b.WriteString("  unset \"$varname\"\n")
	b.WriteString("done < <(compgen -v | grep -E \"^(CLAUDE_|ANTHROPIC_)\")\n\n")

	fmt.Fprintf(&b, "export CLAUDE_CONFIG_DIR=\"%s\"\n", profileDir)
	fmt.Fprintf(&b, "export CLAUDE_PROFILE=\"%s\"\n", name)

	// Custom env vars
	if len(profile.Env) > 0 {
		keys := make([]string, 0, len(profile.Env))
		for k := range profile.Env {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&b, "export %s=\"%s\"\n", k, profile.Env[k])
		}
	}

	b.WriteString("\n")

	// Subcommands bypass
	fmt.Fprintf(&b, "case \"${1:-}\" in\n  %s) exec claude \"$@\" ;;\nesac\n\n", subcommands)

	// Model handling
	if profile.Model != "" {
		b.WriteString("# Default model (overridden if --model is passed on command line)\n")
		b.WriteString("has_model=false\n")
		b.WriteString("for arg in \"$@\"; do\n")
		b.WriteString("  case \"$arg\" in\n")
		b.WriteString("    --model|--model=*) has_model=true; break ;;\n")
		b.WriteString("  esac\n")
		b.WriteString("done\n\n")
	}

	// Build exec command
	var cmdParts []string
	cmdParts = append(cmdParts, "exec claude")
	for _, d := range profile.AddDirs {
		expanded := ExpandPath(d)
		cmdParts = append(cmdParts, fmt.Sprintf("--add-dir \"%s\"", expanded))
	}

	if profile.Model != "" {
		cmdParts = append(cmdParts, fmt.Sprintf("$([ \"$has_model\" = false ] && echo '--model %s')", profile.Model))
	}

	cmdParts = append(cmdParts, "\"$@\"")
	b.WriteString(strings.Join(cmdParts, " \\\n  ") + "\n")

	return b.String()
}

func InstallWrapper(scriptPath, content string) error {
	dir := filepath.Dir(scriptPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	existing, err := os.ReadFile(scriptPath)
	if err == nil && string(existing) == content {
		return nil
	}

	if err := os.WriteFile(scriptPath, []byte(content), 0o755); err != nil {
		return err
	}
	fmt.Printf("  installed %s\n", scriptPath)
	return nil
}

func CleanupStaleScripts(binDir string, activeNames map[string]bool) {
	entries, err := os.ReadDir(binDir)
	if err != nil {
		return
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if activeNames[entry.Name()] {
			continue
		}
		// Wrappers are always named claude-<profile>. Anything else in bin_dir
		// is someone else's binary — including cpm itself, which carries the
		// marker as a compiled-in string constant.
		if !strings.HasPrefix(entry.Name(), wrapperPrefix) {
			continue
		}
		path := filepath.Join(binDir, entry.Name())
		if !isGeneratedWrapper(path) {
			continue
		}
		os.Remove(path)
		fmt.Printf("  removed stale script %s\n", path)
	}
}

// isGeneratedWrapper reports whether path is a shell script cpm generated,
// judged by the marker appearing in its header rather than anywhere in the
// file — a binary that merely embeds the string must not match.
func isGeneratedWrapper(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	head := make([]byte, 512)
	n, err := f.Read(head)
	if err != nil && n == 0 {
		return false
	}
	head = head[:n]

	if !strings.HasPrefix(string(head), "#!") {
		return false
	}
	lines := strings.SplitN(string(head), "\n", markerScanLines+1)
	for i, line := range lines {
		if i >= markerScanLines {
			break
		}
		trimmed := strings.TrimSpace(line)
		if trimmed == marker || trimmed == legacyMarker {
			return true
		}
	}
	return false
}
