package internal

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateWrapperBasic(t *testing.T) {
	profile := &Profile{
		Description: "Personal account",
	}

	out := GenerateWrapper("personal", "/home/user/.claude-profiles/personal", profile)

	mustContain := []string{
		"#!/usr/bin/env bash",
		"Generated by cpm",
		"Profile: personal",
		`CLAUDE_CONFIG_DIR='/home/user/.claude-profiles/personal'`,
		`CLAUDE_PROFILE='personal'`,
		"exec claude",
	}

	for _, s := range mustContain {
		if !strings.Contains(out, s) {
			t.Errorf("wrapper missing %q", s)
		}
	}
}

func TestGenerateWrapperWithModel(t *testing.T) {
	profile := &Profile{
		Description: "Work",
		Model:       "sonnet",
	}

	out := GenerateWrapper("work", "/profiles/work", profile)

	if !strings.Contains(out, "has_model=false") {
		t.Error("wrapper should contain model detection logic")
	}
	if !strings.Contains(out, "--model 'sonnet'") {
		t.Error("wrapper should contain --model sonnet")
	}
}

func TestGenerateWrapperWithAddDirs(t *testing.T) {
	home, _ := os.UserHomeDir()
	profile := &Profile{
		Description: "Work",
		AddDirs:     []string{"~/Work/company"},
	}

	out := GenerateWrapper("work", "/profiles/work", profile)

	expected := filepath.Join(home, "Work/company")
	if !strings.Contains(out, "--add-dir '"+expected+"'") {
		t.Errorf("wrapper should contain --add-dir for %s", expected)
	}
}

func TestGenerateWrapperWithEnv(t *testing.T) {
	profile := &Profile{
		Description: "Vertex",
		Env: map[string]string{
			"CLAUDE_CODE_USE_VERTEX": "1",
			"CLOUD_ML_REGION":        "europe-west1",
		},
	}

	out := GenerateWrapper("vertex", "/profiles/vertex", profile)

	if !strings.Contains(out, `CLAUDE_CODE_USE_VERTEX='1'`) {
		t.Error("wrapper missing CLAUDE_CODE_USE_VERTEX")
	}
	if !strings.Contains(out, `CLOUD_ML_REGION='europe-west1'`) {
		t.Error("wrapper missing CLOUD_ML_REGION")
	}
}

func TestGenerateWrapperSubcommandBypass(t *testing.T) {
	profile := &Profile{Description: "Test"}
	out := GenerateWrapper("test", "/profiles/test", profile)

	for _, sub := range []string{"mcp", "auth", "doctor"} {
		if !strings.Contains(out, sub) {
			t.Errorf("wrapper should handle subcommand %q", sub)
		}
	}
}

func TestInstallWrapper(t *testing.T) {
	dir := t.TempDir()
	scriptPath := filepath.Join(dir, "claude-test")
	content := "#!/usr/bin/env bash\necho test\n"

	if err := InstallWrapper(scriptPath, content); err != nil {
		t.Fatalf("InstallWrapper failed: %v", err)
	}

	data, err := os.ReadFile(scriptPath)
	if err != nil {
		t.Fatalf("cannot read script: %v", err)
	}
	if string(data) != content {
		t.Errorf("script content mismatch")
	}

	info, _ := os.Stat(scriptPath)
	if info.Mode()&0o111 == 0 {
		t.Error("script should be executable")
	}
}

func TestInstallWrapperIdempotent(t *testing.T) {
	dir := t.TempDir()
	scriptPath := filepath.Join(dir, "claude-test")
	content := "#!/usr/bin/env bash\necho test\n"

	InstallWrapper(scriptPath, content)
	info1, _ := os.Stat(scriptPath)

	// Second install with same content should not rewrite
	err := InstallWrapper(scriptPath, content)
	if err != nil {
		t.Fatalf("second InstallWrapper failed: %v", err)
	}

	info2, _ := os.Stat(scriptPath)
	if !info1.ModTime().Equal(info2.ModTime()) {
		t.Error("wrapper should not be rewritten when content is unchanged")
	}
}

func TestCleanupStaleScripts(t *testing.T) {
	dir := t.TempDir()

	// Create a stale script with our marker
	stale := filepath.Join(dir, "claude-old")
	os.WriteFile(stale, []byte("#!/bin/bash\n"+marker+"\necho old\n"), 0o755)

	// Create an active script
	active := filepath.Join(dir, "claude-keep")
	os.WriteFile(active, []byte("#!/bin/bash\n"+marker+"\necho keep\n"), 0o755)

	// Create a non-cpm script
	other := filepath.Join(dir, "other-script")
	os.WriteFile(other, []byte("#!/bin/bash\necho other\n"), 0o755)

	activeNames := map[string]bool{"claude-keep": true}
	CleanupStaleScripts(dir, activeNames)

	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Error("stale script should have been removed")
	}
	if _, err := os.Stat(active); err != nil {
		t.Error("active script should be kept")
	}
	if _, err := os.Stat(other); err != nil {
		t.Error("non-cpm script should be kept")
	}
}

func TestCleanupStaleScriptsKeepsCpmBinary(t *testing.T) {
	dir := t.TempDir()

	// The cpm binary embeds the marker as a compiled-in string constant, so a
	// naive "content contains marker" check makes cpm install delete cpm.
	binary := filepath.Join(dir, "cpm")
	content := append([]byte{0x7f, 'E', 'L', 'F', 0x00, 0x01}, []byte("...\x00"+marker+"\x00...")...)
	os.WriteFile(binary, content, 0o755)

	// Same trap under a claude- name: a wrapper-looking file whose marker sits
	// past the header is not something cpm generated.
	notAWrapper := filepath.Join(dir, "claude-something-else")
	body := "#!/bin/bash\n# line 2\n# line 3\n# line 4\n# line 5\n# line 6\n" + marker + "\n"
	os.WriteFile(notAWrapper, []byte(body), 0o755)

	CleanupStaleScripts(dir, map[string]bool{})

	if _, err := os.Stat(binary); err != nil {
		t.Error("cpm binary must not be removed by its own cleanup")
	}
	if _, err := os.Stat(notAWrapper); err != nil {
		t.Error("file with marker outside the header should be kept")
	}
}

func TestCleanupStaleScriptsRemovesLegacyWrapper(t *testing.T) {
	dir := t.TempDir()

	legacy := filepath.Join(dir, "claude-legacy")
	os.WriteFile(legacy, []byte("#!/usr/bin/env bash\n"+legacyMarker+"\necho legacy\n"), 0o755)

	CleanupStaleScripts(dir, map[string]bool{})

	if _, err := os.Stat(legacy); !os.IsNotExist(err) {
		t.Error("wrapper from a pre-rename version should be removed")
	}
}
